server:
  port: 8084

spring:
  application:
    name: notification-service

httpClients:
  message-service: http://message-service/msg/api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"