server:
  port: 8080

spring:
  application:
    name: notification-gateway
  cloud:
    gateway:
      routes:
        - id: email-filtering-service
          uri: lb://email-filtering-service
          predicates:
            - Path=/filtering/api/**
            - Method=GET,POST,DELETE,PUT,OPTIONS
        - id: email-rest-client
          uri: lb://email-rest-client
          predicates:
            - Path=/email/api/**
            - Method=GET,POST,DELETE,PUT,OPTIONS
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/msg/api/**
            - Method=GET,POST,DELETE,PUT,OPTIONS
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost