server:
  port: 8083

spring:
  profiles:
    active: dev
  application:
    name: message-service

springdoc:
  swagger-ui:
    path: "/msg/api/docs"
  api-docs:
    path: "/msg/api/api-docs"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
