server:
  port: 8083
  servlet:
    context-path: "/msg/api"

spring:
  profiles:
    active: dev
  application:
    name: message-service

httpClients:
  message-service: http://message-service/msg/api

springdoc:
  swagger-ui:
    path: "/docs"
  api-docs:
    path: "/api-docs"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"