server:
  port: 8081
  servlet:
    context-path: "/email/api"

spring:
  profiles:
    active: dev
  application:
    name: email-rest-client
  gmail:
    refresh:
      token: ${GMAIL_REFRESH_TOKEN}

springdoc:
  swagger-ui:
    path: "/docs"
  api-docs:
    path: "/api-docs"

httpClients:
  email-filtering-service: http://email-filtering-service/filtering/api
  message-service: http://message-service/msg/api

eureka:
  client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"