{
 "title": "Notification Microservices",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Email Rest Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Application runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"email-rest-client\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (process_cpu_usage{job=\"email-rest-client\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{job=\"email-rest-client\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"email-rest-client\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB calls invocations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by() (spring_data_repository_invocations_seconds_count{job=\"email-rest-client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB connections total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{job=\"email-rest-client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch emails",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "fetch_email_seconds{job=\"email-rest-client\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Fetch emails total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fetch_email_seconds_count{job=\"email-rest-client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch emails total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fetch_email_seconds_sum{job=\"email-rest-client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filtering Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Application runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"filtering-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (process_cpu_usage{job=\"filtering-service\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{job=\"filtering-service\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"filtering-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB calls invocations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_data_repository_invocations_seconds_count{job=\"filtering-service\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB connections total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{job=\"filtering-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtering email requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "filter_email_seconds{job=\"filtering-service\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Filtering email total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "filter_email_seconds_count{job=\"filtering-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filter email request total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "filter_email_seconds_sum{job=\"filtering-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Message Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Application runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"message-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (process_cpu_usage{job=\"message-service\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{job=\"message-service\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"message-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB calls invocations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_data_repository_invocations_seconds_count{job=\"message-service\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB connections total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create message requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "create_message_manually_seconds{job=\"message-service\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Crate message manually total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(create_message_manually_seconds_count{job=\"message-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create message manually total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(create_message_manually_seconds_sum{job=\"message-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BREAKING POINT",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "create_message_from_emails_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create message from email requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "create_message_from_emails_seconds{job=\"message-service\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Crate message from email total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "create_message_from_emails_count{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create message form email total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "create_message_from_emails_sum{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BREAKING POINT",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "create_message_from_emails_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update message requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "update_message_seconds{job=\"message-service\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Update message total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "update_message_count{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update message total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "update_message_sum{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BREAKING POINT",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "create_message_from_emails_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get messages requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "get_messages_seconds{job=\"message-service\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Get messages total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "get_messages_seconds_count{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get messages total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "get_messages_seconds_sum{job=\"message-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Notification Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Application runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"notification-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (process_cpu_usage{job=\"notification-service\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{job=\"notification-service\"})",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"notification-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Notify total requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_notify_seconds_count{job=\"notification-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify total time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_notify_seconds_sum{job=\"notification-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "notification_notify_seconds{job=\"notification-service\"}",
     "legendFormat": "{{quantile}} {{method}} {{uri}}"
    }
   ]
  }
 ]
}